### ISSUE TITLE
[FR] Order but not renaming

### ISSUE THREAD

**Issue by bonnebulle** [hellt/markdown-footnote-sorter#1]
Hello, thanks for answering https://github.com/derdennis/sort-markdown-footnotes/issues/2
This one, here, works (using curl)
But... no options for now.
I would like to sort footnotes... without renaming them

So, we can imagine some option/parameters : 
- at the end of the document /or/ after the paragraph
- reordering and renaming (1,2,3..) /or/ reordering **without renaming**

...
am searching for this very last option 
: I want to sort my footnotes at the end of my .md file
: but I would like to keep the names I give

Final result/example (order by progression order) :
```
Mon text de bienvenue[^text_hello], en français[^langue]

[^text_hello]: exemple
[^langue]: but you can translate it :)
```
Sorry, I dont have the skills to re.code it in python, I just can read regex101, thanks for your work

**Comment by mjbear** [comment]
@bonnebulle 
I'll give this feature request some thought.

**Comment by mjbear** [comment]
@bonnebulle @hellt 
I have a solution for this, but I'm holding off until a pending PR #13 (from today) is considered.

My reasoning is that I suspect there could be some merge conflicts that I'll have to iron out based on the pending PR. Thank you for understanding.

**Comment by mjbear** [comment]
@bonnebulle 
PR #14 is waiting for @hellt's review.

As I worked through the last PR and this one I have some refactoring I want to tinker with ... but this does work! :rocket: :grinning: 

Enjoy.
While I didn't intend to do this in return for anything if anyone wants to say thanks you could [buy me a coffee](https://buymeacoffee.com/mjbear). :sweat_smile:
