### ISSUE TITLE
Linting and Formatters

### ISSUE THREAD

**Issue by mjbear** [hellt/markdown-footnote-sorter#17]
Hello @hellt

What are your thoughts on adding further development tooling to the project and GH Actions?
* linter(s)
* formatter(s)

(If it's ok,) Might you have any preference on the tool or tools to use?

Thank you!

**Comment by hellt** [comment]
Hi @mjbear 
yes, please check out ruff - https://docs.astral.sh/ruff/
both linter and formatter

**Comment by mjbear** [comment]
> Hi @mjbear yes, please check out ruff - https://docs.astral.sh/ruff/ both linter and formatter

I'll take a look at ruff

We're certainly most interested in Python linting and formatting. :wink:
There's also a markdown linter which I'll look into running locally first to see what it finds or how it behaves. :sweat_smile: 
https://github.com/markdownlint/markdownlint

**Comment by mjbear** [comment]
So far I haven't exactly found one that stands out as an exceptionally popular MD linter.

* https://github.com/markdownlint/markdownlint
    * ruby
    * GH action: https://github.com/marketplace/actions/run-markdownlint-mdl
* https://github.com/igorshubovych/markdownlint-cli
    * javascript
    * GH action: https://github.com/marketplace/actions/markdown-linting-action
* https://github.com/btford/write-good
   * javascript
   * GH action: https://github.com/marketplace/actions/lint-markdown
* https://github.com/jackdewinter/pymarkdown/tree/main
    * python
    * pypi - https://pypi.org/project/pymarkdownlnt/
* https://github.com/DavidAnson/markdownlint
    * nodejs

**Comment by hellt** [comment]
I use markdownlint in my docs

**Comment by hellt** [comment]
maybe after footnote sorted you can enhance https://github.com/hellt/pymdowx-block-converter which is another important tool in the mkdocs toolchain  =)

**Comment by mjbear** [comment]
@hellt
The markdown linting is more of a pain than I figured. (It's creating character and experience though. :rofl:)
Worked through a bunch of the md linting, but not all of it so far.

[mdl-action](https://github.com/marketplace/actions/run-markdownlint-mdl) is hard-coded to run against the current dir `.`

And the README.md has some warts still even after all the clean up I've done.

* mdl doesn't like inline HTML, which is necessary to resize an image in README.md
   * one option is to leave the image in its original size
* mdl doesn't like the long line for the HTML img tag in README.md
   * possibly remedied if I go with the full size image

**Comment by hellt** [comment]
you can disable rules in .mardownlint.yml to silence annoying things

**Comment by mjbear** [comment]
> you can disable rules in .mardownlint.yml to silence annoying things

Agreed.
I'm less concerned about disabling the inline HTML, but it seems like an issue to disable the line length checks.

With some [enhancement to mdl-action](https://github.com/bewuethr/mdl-action/pull/36) now it supports specifying a directory :grinning:

I'll still probably see if there's a means to resize the image without having to upload a static one.

**Realization:**
Oh, the markdownlint I was using has *.rb files. Maybe I'm using the wrong one.
Is this an issue?
Would you be able to share the `uses:` line so I at least know what markdownlint action you meant?

**Comment by hellt** [comment]
I haven't used an action before 
But if id do that I would probably install it and use it as a make target so that it can be called by a user outside of gh actions as well

**Comment by mjbear** [comment]
> I haven't used an action before But if id do that I would probably install it and use it as a make target so that it can be called by a user outside of gh actions as well

@hellt
Makes sense.
Totally agree. I was also thinking a next step would be to set up local testing as well.

* I ran linting locally to fix up issues
* Add GH Action to run on PR and so on
* [soon in the future] Add a means for bundling local package management and testing

I'll investigate the Node.js version of markdownlint/markdownlint-cli2 since that uses .markdownlint.yml

:rocket: :moon: :ringed_planet:

**Comment by mjbear** [comment]
Hello @hellt 

I have the Markdown linting PR #19 ready for your review.

I have others staged as drafts since there will be merge conflicts (example being more than one modifies ci.yml).

Thank you!

**Comment by mjbear** [comment]
@hellt
Does it make sense to lint the Dockerfile via GH Actions?
Thank you.

(If yes) Like the others, using Docker images...

* https://github.com/replicatedhq/dockerfilelint
   * GH Action - https://github.com/marketplace/actions/docker-lint
* https://github.com/hadolint/hadolint
   * GH Action - https://github.com/marketplace/actions/hadolint-action

**Comment by hellt** [comment]
I don't think so, docker file is very small in this instance
