### ISSUE TITLE
Enhancement - Unit Tests

### ISSUE THREAD

**Issue by mjbear** [hellt/markdown-footnote-sorter#2]
Hello @hellt,

Would you be open to adding unit testing to the project?
(I'm asking as that's something I'd like to work on as a contribution.)

I figured I'd contain things to the standard library so I started tinkering with unittest instead of pytest (but pytest is backwards compatible or the tests can be later rewritten).

Thoughts :question: 

For what it's worth:
- I've noticed some interesting behavior when it comes to the file's EOL.
- With the unit testing one of us (maybe me) can hack on derdennis/sort-markdown-footnotes/issues/1 or #1 and any other issues and determine whether code regressions occur. :sunglasses:

**Comment by hellt** [comment]
Hi
feel free to augment this with tests for sure
