### ISSUE TITLE
Enhancement - function name and f-string

### ISSUE THREAD

**Issue by mjbear** [hellt/markdown-footnote-sorter#4]
Hello @hellt,

Note:
- Please let me know if you would rather I lump several changes in a PR or break them out.
- Or if there are any contributing guidelines or discussion we need to have before I work up changes.
<hr/>

https://github.com/hellt/markdown-footnote-sorter/blob/main/fnsort.py#L45

1. Do you have an objection to a PR to change `def refrepl` to be more descriptive?
    -  Such as `def replace_ref` (or even `def replace_reference` should we want it fully spelled out).
       - :bulb: I'm in support of the fully spelled out function name.
1. In addition, since this is Python3 would you be amenable to replacing ["old string formatting"](https://docs.python.org/3/tutorial/inputoutput.html#old-string-formatting) with [f-strings](https://docs.python.org/3/tutorial/inputoutput.html#formatted-string-literals)?
    - `return "%s[^%s]" % (m.group(0)[:1], order.index(m.group(2)) + 1)`
        - becomes `return f"{m.group(0)[:1]}[^{order.index(m.group(2)) + 1}]"`
    - If the format string isn't "readable" enough, maybe stash values (ex: `m.group(0)[:1]`) in variables that can be used in a more readable f-string.

There is also another "old string" that I'd replace as well (for `newlabels`).

Thank you! :grinning:

**Comment by hellt** [comment]
Hi

* small PRs work better
* f strings are good
* renaming for clarity is great

**Comment by mjbear** [comment]
Hello @hellt,

Once #6 for the EOL at EOF issue, then I'll rebase my next feature branch and progressively continue that as each PR is merged. (I'm doing it this way so it's an easy fast-forward merge!)

I'm planning on this order:
1. f-strings
1. renaming a function name

Then chase a couple other items ... haha :grinning:

**Comment by mjbear** [comment]
PRs #8 (f-strings) and #9 (refrepl func name) resolve this issue ticket.
